# Generated by Django 4.0.3 on 2022-03-23 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_comment_options_book_dislikes_book_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('add_like', 'Can add like'), ('add_dislike', 'Can add dislike'))},
        ),
    ]
