#!/bin/bash



#ls *.txt > /dev/null 2>&1
#if [ $? -ne 0 ]; then
#	echo "Directory contains 0 *.txt files"
#else
#	let i=0
#	for a in *.txt; do
#		let i++;
#	done
#	echo "Directory contains $i *.txt files"
#fi

#counter=10
#while [ $counter -gt 0 ]; do
#	echo "Counting down: $counter";
#	let counter--; 
#	sleep 1;
#done

#count=43
#if [ $count -eq 42  ]; then
#	echo "42 is correct"
#elif [ $count -gt 42 ]; then 
#	echo "Too much"
#else echo "Not enough"
#fi

#for i in {1..10}; do
#	echo "Counting: $i"
#	sleep 1
#done
